config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  # get 'users/new' , as: 'signup'
  get  '/signup',   to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :items do
    member do
      patch :complete
    end
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  
  def completed?
      !completed_at.blank?
  end
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :show, :update, :destroy]
  before_action :logged_in_user, only: [:index]
  before_action :find_item, only: [:show, :edit, :update, :destroy]
  
  def index
    if logged_in?
      @items = Item.where(:user_id => current_user.id).order("created_at DESC")
    end
  end
  
  def show
  end
  
  def new
    @item = current_user.items.build
  end
  
  def create
    @item = current_user.items.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end
  
  def destroy
    @item.destroy
    redirect_to items_path
  end
  
  def complete
    @item = Item.find(params[:id])
    @item.update_attribute(:completed_at, Time.now)
    redirect_to items_path
  end
  
  private
  
    def item_params
      params.require(:item).permit(:title, :description)
    end
    
    def find_item
      @item = Item.find(params[:id])
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<% provide(:title, 'Edit checklist') %>
<h1>アイテム編集</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@item, url: item_path) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.submit "アイテム変更", class: "btn btn-primary btn-lg" %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<% provide(:title, "Checklists") %>
<% if logged_in?%>
 <div style="padding-top:20px;">
  <% @items.each do |item| %>
   
   <div class="row item">
    <% if item.completed?%>
        <div class="col-md-3">
        </div>
      
        <div class="col-md-4">
          <h3 style="opacity:0.5;" class="item-title"><strike><%= link_to item.title, item %></strike></h3>
          <p style="opacity:0.5;" class="item-sub-title item-desc"><%= item.description %></p>
          <p style="opacity:0.5;" class="time-ago item-sub-title"><%= time_ago_in_words(item.completed_at)%>前に作成した</p>
        </div>
        <div class="col-md-1">
          <p><%= link_to complete_item_path(item), method: :patch do %></p>
             <i class="fa fa-lf fa-check" ></i>
          <% end %>
        </div>
        <div class="col-md-1">
          <p><%= link_to item, method: :delete, data: { confirm: "本当によろしいでしょうか？" } do %></p>
             <i class="fa fa-lf fa-trash"></i>
          <% end %>
        </div>
        
        <div class="col-md-3">
        </div>
      
    <% else %>
        <div class="col-md-3">
        </div>
      
        <div class="col-md-4">
          <h3 class="item-title"><%= link_to item.title, item %></h3>
          <p class="item-sub-title item-desc"><%= item.description %></p>
          <p class="time-ago item-sub-title"><%= time_ago_in_words(item.created_at)%>前に作成した</p>
        </div>
        <div class="col-md-1">
          <p><%= link_to complete_item_path(item), method: :patch do %></p>
             <i class="fa fa-lf fa-check"></i>
          <% end %>
        </div>
        <div class="col-md-1">  
          <p><%= link_to item, method: :delete, data:{ confirm: "本当によろしいでしょうか？" } do %></p>
             <i class="fa fa-lf fa-trash"></i>
          <% end %>
        </div>
        
        <div class="col-md-3">
        </div>
        
    <% end %>
   </div>
    
  <% end %>
  </div>
  <!--<div><#%= link_to "New Item", new_item_path %></div>-->
<% end %>

app/views/items/new.html.erb
<% provide(:title, 'New checklist') %>
<h1>アイテム作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@item, url: items_path) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.submit "アイテム作成", class: "btn btn-primary btn-lg" %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<% provide(:title, @item.title) %>
<h3><%= @item.title %></h3>
<p><%= @item.description %></p>

<%= link_to items_path do %>
<button type="button" class="btn btn-primary">戻る</button>
<% end %>
<%= link_to edit_item_path(@item) do %>
<button type="button" class="btn btn-success">編集</button>
<% end %>
<%= link_to item_path(@item), method: :delete, data: {confirm: "本当によろしいでしょうか？"} do %>
<button type="button" class="btn btn-danger">削除</button>
<% end %>