config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  # get 'users/new' , as: 'signup'
  get  '/signup',   to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :items do
    member do
      patch :complete
    end
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This application was made by 渡部肇志
  </small>
  <nav>
    <ul>
      <!--<li><#%= link_to "About",   about_path %></li>-->
      <li><%= link_to "お問い合わせ", contact_path %></li>
      <li><a href="https://railstutorial.jp/">参考</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="pc">
      <%= link_to "成功の物語(チェックリスト/情報共有アプリ)", root_path, id: "logo" %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "ヘルプ", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "チェックリスト", items_path %></li>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "チェックリスト作成", new_item_path %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
    <nav class="smart-phone">
      <%= link_to "成功の物語", root_path, id: "logo" %>
      <div class="wrapper">
        <input type="checkbox" class="toggler">
        <div class="hamburger">
          <div></div>
        </div>
        <div class="menu">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "ホーム", root_path %></li>
            <li><%= link_to "ヘルプ", help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "チェックリスト", items_path %></li>
              <li><%= link_to "ユーザー一覧", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "プロフィール", current_user %></li>
                  <li><%= link_to "チェックリスト作成", new_item_path %></li>
                  <li><%= link_to "設定", edit_user_path(current_user) %></li>
                  <!--<li class="divider"></li>-->
                  <li>
                    <%= link_to "ログアウト", logout_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "ログイン", login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>
<!--<script>-->
<!--  $(function(){-->
<!--  	$('#nav_toggle').click(function(){-->
<!--			$("nav.smart-phone").toggleClass('open');-->
<!--		  $("nav").slideToggle(500);-->
<!--		});-->
<!--  });-->
<!--</script>-->

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
        <div class ="step">
          <%= image_tag "step.jpg" %>
        </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>